apiVersion: v1
kind: Secret
metadata:
  name: alex-website-secrets
  namespace: alex-website
type: Opaque
data:
  ALEX_API_KEY: YWd3TEp6d0pLTjkyWFJCbi00Y2Z5aXcyTk5qZDUtR2hKb2xBQXlGang1awo=  # Replace with actual base64-encoded API key
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: alex-website
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "YW5vcnVtOmdocF9vNWpGZ2lmUG5VN1lkQUhKUFRDYWJRVW5pYU54TWwwZ2tUanU="
        }
      }
    }